export const contents: Record<string, string> = {
  "1": "The quick brown fox jumped over the lazy dog.",
  "2": "A red apple hangs from the tree.",
  "3": "The sun sets over the horizon, painting the sky with vibrant colors.",
  "4": "In a galaxy far, far away, a heroic adventure unfolds.",
  "5": "Roses are red, violets are blue, sugar is sweet, and so are you.",
  "6": "The gentle breeze rustles the leaves of the tall oak trees.",
  "7": "The scientist made a groundbreaking discovery that changed the world.",
  "8": "A warm cup of tea on a rainy day is pure comfort.",
  "9": "Mysterious footsteps echoed through the abandoned mansion.",
   "10": "The ancient ruins hold secrets from a forgotten civilization.",
   "11": "A rainbow appeared in the sky after the rain.",
   "12": "The astronaut gazed at the stars from the space station.",
   "13": "An old bookshop on the corner of the street had a magical charm.",
   "14": "The waves crashed against the rocky shore with tremendous force.",
   "15": "The wise sage shared his wisdom with the eager disciples.",
   "16": "A roaring waterfall cascaded down the mountain",
   "17": "The detective solved the perplexing case using his sharp wit.",
   "18": "A field of colorful flowers stretched as far as the eye could see.",
   "19": "The chef prepared a delectable feast with exquisite flavors.",
   "20": "Children played joyfully in the park on a sunny day.",
   "21": "The grand orchestra performed a symphony that moved the audience to tears.",
   "22": "An ancient treasure map led explorers on an exciting quest.",
   "23": "The thunderstorm raged on, lightning illuminating the night sky.",
   "24": "The mountain peak offered a breathtaking view of the valley below.",
   "25": "The painter's masterpiece captured the essence of nature's beauty.",
   "26": "A charming cottage nestled in the woods proa peaceful retreat.",
   "27": "A gentle river meandered through the serene country",
   "28": "The starry night sky inspired poets and dreamers alike.",
   "29": "A magical portal transported adventurers to a different realm.",
   "30": "The storyteller captivated the audience with tales of mythical creatures.",
   "31": "A garden in full bloom was a sight to behold.",
   "32": "The bustling city streets came alive with the sounds of the night.",
   "33": "A secret passage led to  chambers beneath the castle.",
   "34": "The brave knight embarked on a quest to rescue the captured princess.",
   "35": "A mysterious message arrived in an old, dusty envelope.",
   "36": "The scent of fresh flowers filled the air in the garden.",
   "37": "A shooting star streaked across the night sky, granting wishes.",
   "38": "The ancient tree in the forest was s have magical powers.",
   "39": "A symphony of chirping birds greeted the dawn.",
   "40": "The time traveler journeyed to distant eras of the past and future.",
   "41": "A  treasure chest was buried on a remote island.",
   "42": "The ht train carried passengers to unknown destinations.",
   "43": "A mysterious lighthouse gships safely through the stormy sea.",
   "44": "The enchanted forest was home to mythical creatures.",
   "45": "A cozy cabin by the lake offered solace and serenity.",
   "46": "The ancient castle held secrets from centuries past.",
   "47": "A forgotten diary revealed the life of a bygone era.",
   "48": "The mesmerizing dance of fireflies lit up the night.",
   "49": "A mystical potion granted extraordinary powers to those who drank it.",
   "50": "The old library contained books of wisdom and adventure.",
 }
  